name: Node.js CI/CD to AWS ECR and EKS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ap-northwest-1 # Replace with your AWS region
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t my-nodejs-app:${{ github.sha }} .

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Push Image to Amazon ECR
      run: |
        docker tag my-nodejs-app:${{ github.sha }} ${{ steps.login-ecr.outputs.registry }}/my-nodejs-app:${{ github.sha }}
        docker push ${{ steps.login-ecr.outputs.registry }}/my-nodejs-app:${{ github.sha }}

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1

    - name: Deploy to Kubernetes
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config
        kubectl set image deployment/my-nodejs-app-deployment my-nodejs-app-container=${{ steps.login-ecr.outputs.registry }}/my-nodejs-app:${{ github.sha }}
